name: Build, Push, and Deploy Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/r-a-l-ai/middleware-strapi:${{ github.ref_name }}
          ghcr.io/r-a-l-ai/middleware-strapi:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to server
      run: |
        curl -k -X POST "https://portainer.platform.horizonfinder.cz/api/stacks/webhooks/40e8b3a0-c8b7-4d90-b477-0f7371d5237e?IMAGE_VERSION=${{ github.ref_name }}"
